### ISSUE TITLE
Kelime Import

### ISSUE THREAD

**Issue by sdilsiz** [berat/wordBox-react-native#1]
Merhaba Berat Bey , 
Elimizde olan kelime listesini nasil uygulamaya import edebiliriz? 
Tesekkurler

**Comment by berat** [comment]
Merhaba @sdilsiz ,

Şu an öyle bir seçenek bulunmuyor. Ama uygulamayı yakın zamanda geliştirmeye devam edeceğim. O zaman bu özelliği düşünebilirim .

**Comment by sdilsiz** [comment]
hizli cevabiniz icin tesekkur ederim.
elimde bir kelime listesi var.
kelime tipi/ aciklamasi ve ornek bir cumle seklinde.
onu import ederek biraz tekrar edeyim istemistim.
o yuzden sormustum.

**Comment by berat** [comment]
Aslında uygulamayı kelime / anlamı / örnek cümle ve sesli okunuşu şeklinde düşünmüştüm ama şu an sadece kelime ve anlamı olarak kullanılıyor.

İlerleyen zamanlarda örnek cümle içinde kullanımı da gelecektir. Ama sesli okunuşu için google'a ödeme yapmam gerekiyor, Ücretsiz bir şey bulamadım. İlerleyen zamanlarda eğer uygulamanın getiri olursa bu özelliği de devreye sokarız.

**Comment by sdilsiz** [comment]
Anladim tesekkur ederim Berat Bey. kolay gelsin. aktif kullanmamistim. aktif olarak kullandigim zaman karsilasirsam yeni istekler iletirim diye dusunuyorum. Tesekkurler. Iyi calismalar
